Chainspec upgrade - berlin HF
energywebfoundation/ewf-chainspec pull request #14
Opened 2021-06-01 12:22 UTC by KaamilW

2021-06-02 10:12 UTC, ngyam requested changes

2021-06-14 12:27 UTC, ngyam requested changes
Please update the checksums too in the readme. Other than that, LGTM.

2021-06-14 13:02 UTC, ngyam approved these changes
LGTM

2021-06-14 15:23 UTC, royki approved these changes
- `SHA256(EnergyWebChain.json)= 079fc95aa56bfe37daaeaa673fc4941d451c2d2ed22c6b633a8a448de088de49`

- EnergyWebChain - `Hex(12565478) = BFBBE6`

- `SHA256(Volta.json)= 38fb5371cde639799c18cb25fa83c679044c39434c63d6610dc3f300f8f30894`
- Volta `Hex(12209759) = BA4E5F`

Looks Good.

2021-06-14 22:31 UTC, ngyam approved these changes

2021-06-15 07:10 UTC, merged